package com.opspilot.task;
import static org.junit.jupiter.api.Assertions.*; import java.lang.reflect.*; import java.time.LocalDate; import java.util.*; import com.opspilot.project.*; import com.opspilot.task.dto.*; import com.opspilot.user.*; import com.opspilot.workspace.*; import org.junit.jupiter.api.Test;
class TaskServiceTest {
 @Test void memberCreatesTodoWithMediumPriorityAndCreator()throws Exception{S s=new S();User u=s.u("u");Workspace w=s.w(u);s.m(w,u);Project p=s.p(w,u);TaskResponse t=s.s().create(p.getId(),u.getId(),new CreateTaskRequest("T",null,null,null,LocalDate.of(2026,8,25)));assertEquals(TaskStatus.TODO,t.status());assertEquals(TaskPriority.MEDIUM,t.priority());assertEquals(u.getId(),t.creator().id());assertNull(t.assignee());assertEquals(LocalDate.of(2026,8,25),t.dueDate());}
 @Test void assigneeMustBeWorkspaceMemberAndFiltersWork()throws Exception{S s=new S();User a=s.u("a"),b=s.u("b"),out=s.u("out");Workspace w=s.w(a);s.m(w,a);s.m(w,b);Project p=s.p(w,a);TaskService x=s.s();TaskResponse t=x.create(p.getId(),a.getId(),new CreateTaskRequest("T",null,TaskPriority.HIGH,b.getId(),null));assertEquals(b.getId(),t.assignee().id());assertThrows(InvalidTaskAssigneeException.class,()->x.create(p.getId(),a.getId(),new CreateTaskRequest("Bad",null,null,out.getId(),null)));assertEquals(1,x.list(p.getId(),a.getId(),null,TaskPriority.HIGH,null).size());assertEquals(1,x.list(p.getId(),a.getId(),null,null,b.getId()).size());}
 @Test void updatesStatusUnassignsAndArchivedProjectsRemainReadableButLocked()throws Exception{S s=new S();User u=s.u("u");Workspace w=s.w(u);s.m(w,u);Project p=s.p(w,u);TaskService x=s.s();TaskResponse t=x.create(p.getId(),u.getId(),new CreateTaskRequest("T","D",null,u.getId(),null));assertEquals(TaskStatus.IN_PROGRESS,x.status(t.id(),u.getId(),new UpdateTaskStatusRequest(TaskStatus.IN_PROGRESS)).status());assertNull(x.update(t.id(),u.getId(),new UpdateTaskRequest("New",null,TaskPriority.HIGH,null,null,true,true)).assignee());p.archive();assertNotNull(x.get(t.id(),u.getId()));assertThrows(ArchivedProjectException.class,()->x.create(p.getId(),u.getId(),new CreateTaskRequest("No",null,null,null,null)));assertThrows(ArchivedProjectException.class,()->x.status(t.id(),u.getId(),new UpdateTaskStatusRequest(TaskStatus.DONE)));}
 static class S{List<User>us=new ArrayList<>();List<WorkspaceMember>ms=new ArrayList<>();List<Project>ps=new ArrayList<>();List<Task>ts=new ArrayList<>();long i=1;
 TaskService s(){WorkspaceMemberRepository m=mr();return new TaskService(tr(),pr(),ur(),new WorkspaceAccessService(m));}User u(String e)throws Exception{User u=new User(e,"h",e);life(u,"setCreationTimestamps");id(u);us.add(u);return u;}Workspace w(User o)throws Exception{Workspace w=new Workspace("w",o);life(w,"setCreationTimestamps");id(w);return w;}void m(Workspace w,User u)throws Exception{WorkspaceMember m=new WorkspaceMember(w,u,WorkspaceRole.MEMBER);life(m,"setJoinedAt");id(m);ms.add(m);}Project p(Workspace w,User u)throws Exception{Project p=new Project(w,"p",null,u);life(p,"created");id(p);ps.add(p);return p;}
 UserRepository ur(){return px(UserRepository.class,(m,a)->m.getName().equals("findById")?us.stream().filter(x->x.getId().equals(a[0])).findFirst():bad(m));}WorkspaceMemberRepository mr(){return px(WorkspaceMemberRepository.class,(m,a)->m.getName().equals("findByWorkspace_IdAndUser_Id")?ms.stream().filter(x->x.getWorkspace().getId().equals(a[0])&&x.getUser().getId().equals(a[1])).findFirst():bad(m));}ProjectRepository pr(){return px(ProjectRepository.class,(m,a)->m.getName().equals("findById")?ps.stream().filter(x->x.getId().equals(a[0])).findFirst():bad(m));}TaskRepository tr(){return px(TaskRepository.class,(m,a)->{if(m.getName().equals("saveAndFlush")){Task t=(Task)a[0];if(t.getId()==null){life(t,"created");id(t);ts.add(t);}else life(t,"updated");return t;}if(m.getName().equals("findById"))return ts.stream().filter(x->x.getId().equals(a[0])).findFirst();if(m.getName().startsWith("findByProject"))return ts.stream().filter(x->x.getProject().getId().equals(a[0])).toList();return bad(m);});}
 @SuppressWarnings("unchecked")<T>T px(Class<T>c,H h){return(T)Proxy.newProxyInstance(c.getClassLoader(),new Class[]{c},(q,m,a)->m.getName().equals("toString")?"s":h.go(m,a));}interface H{Object go(Method m,Object[]a)throws Throwable;}static Object bad(Method m){throw new UnsupportedOperationException(m.getName());}void id(Object x)throws Exception{Field f=x.getClass().getDeclaredField("id");f.setAccessible(true);f.set(x,i++);}static void life(Object x,String n)throws Exception{Method m=x.getClass().getDeclaredMethod(n);m.setAccessible(true);m.invoke(x);}}
}
